### ISSUE TITLE
Remove `libnuma` installations

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/miniforge-cuda#22]
In #19, we added `libnuma` installations to our images since they are required for `ucx` and weren't previously available via `conda-forge`.

However, this may change based on the discussions in the issue below.

- https://github.com/conda-forge/ucx-split-feedstock/issues/112

Pending the outcome of that issue, we should remove the `libnuma` installs from our images.

**Comment by ajschmidt8** [comment]
@pentschev, are we safe to remove `libnuma` from these images now?

I assume so. Just want to check.

The lines are below for reference:

https://github.com/rapidsai/miniforge-cuda/blob/f7276218b12904b0ffe2995fc5484b01a3498fd8/Dockerfile#L47-L57

**Comment by pentschev** [comment]
Absolutely, `libnuma` dependency has not been required for 1-2 years, anything that's left over can be wiped out.

**Comment by ajschmidt8** [comment]
Opened https://github.com/rapidsai/miniforge-cuda/pull/59 to remove it.

**Comment by pentschev** [comment]
> This requires `ucx` packages with version `1.14.0`+
> 
> We should confirm that is a minimum in RAPIDS
> 
> xref: [conda-forge/ucx-split-feedstock#111](https://github.com/conda-forge/ucx-split-feedstock/pull/111)

It is: https://github.com/rapidsai/integration/blob/7437cb3bf1bf5b9055f5452a490f1b36d8838e42/conda/recipes/versions.yaml#L18

**Comment by jakirkham** [comment]
Please see this issue: https://github.com/rapidsai/build-planning/issues/27
