### ISSUE TITLE
mambaforge-cuda with "devel" pieces of the CUDA toolkit?

### ISSUE THREAD

**Issue by bdice** [rapidsai/miniforge-cuda#49]
I talked with @csadorf today and it seems like there might be a useful layer between `mambaforge-cuda` and `ci-imgs` that could include the CUDA Toolkit (so that compilers / etc are present) but not the pieces specific to RAPIDS CI. I'd propose this would be something like `mambaforge-cuda-devel`, or a tag on the existing repo. It's hard to get a CUDA 11 container with both mamba/conda and CUDA compilers, and this problem has come up at least 3 times in my experience now.

(CUDA 12 is a bit simpler because the compiler and entire CUDA Toolkit can be installed via conda.)

**Comment by jakirkham** [comment]
Yeah seems like a good idea

How much of the CUDA Toolkit would it include?

**Comment by bdice** [comment]
I think the nvidia/cuda devel images include a full CUDA Toolkit.

**Comment by bdice** [comment]
Now that CUDA 12 is fully available via conda, it might only make sense to have this for CUDA 11. I think I'm going to defer making any changes here unless/until I need it once again, but hopefully development work will shift towards CUDA 12 enough that this won't be needed at all.

**Comment by jakirkham** [comment]
Given the simplifications now possible for CUDA 12, have filed a new issue to explore that: https://github.com/rapidsai/miniforge-cuda/issues/70

**Comment by bdice** [comment]
As of https://github.com/rapidsai/ci-imgs/pull/167, this repository is being moved into `ci-imgs`, so I am cleaning up this issue tracker.

I have not needed this feature for almost a year, so I am closing this issue. Also we will be dropping CUDA 11 support at some point in the future, which will negate the desire for this entirely.
