### ISSUE TITLE
GHA jobs fail because of too many requests

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/miniforge-cuda#72]
Have started seeing GHA jobs fail because of too many request (for [example]( https://github.com/rapidsai/miniforge-cuda/actions/runs/9946474269/job/27477103634?pr=71#step:7:1219 ):

```
#16 ERROR: toomanyrequests: 
------
 > pushing rapidsai/staging:miniforge-cuda-71-cuda12.0.1-base-rockylinux8-py3.9-arm64 with docker:
```

Should we consider some changes here to mange this?

1. Reduce number of images built
2. Add a shared `docker pull` step to minimize pulls and reuse across builds
3. Combine all pushes into a single command at the end
4. Minimize how many jobs are run at once
5. Other ideas?

Note: This happens with `ci-imgs` too ( https://github.com/rapidsai/ci-imgs/issues/162 )

**Comment by ajschmidt8** [comment]
The quickest solution is probably just to adjust the number of concurrent jobs that are allowed in the matrix workflow:

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#defining-the-maximum-number-of-concurrent-jobs

**Comment by bdice** [comment]
Closing in favor of https://github.com/rapidsai/ci-imgs/issues/162, now that `miniforge-cuda` is being merged into `ci-imgs` (https://github.com/rapidsai/ci-imgs/pull/167).
